paths: {
  local: ${DREMIO_HOME}"/data"
  # pdfs: "/opt/dremio/pdfs"   # optionnel, par défaut c'est ça
}

services: {
  coordinator: {
    enabled: true
    master: {
      enabled: true
      embedded-zookeeper: {
        enabled: true
        port: 2181
      }
    }
  }
  executor: {
    enabled: true   # Tu peux laisser le coordinator faire aussi executor (recommandé en petit cluster)
  }
}

zookeeper: "ea-dremio-coordinator:2181"