paths: {
  local: ${DREMIO_HOME}"/data"
  # pdfs: "/opt/dremio/pdfs"   # par défaut
}

services: {
  coordinator: {
    enabled: false
  }
  executor: {
    enabled: true
  }
}

zookeeper: "ea-dremio-coordinator:2181"